<?php
 

$title = 'Delete product';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete ?</p>

<table class="table">
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
    <th>Photo</th>

    <tr>
        <td><p><?=$this->escapeHtml($product->name)?></p></td>
        <td><p><?=$this->escapeHtml($product->description)?></p></td>
        <td><p><?=$this->escapeHtml($product->price)?></p></td>
        <td><p> 
                <a href="<?= $this->escapeHtml($product->photo)?>">
                    <img src="<?=$this->escapeHtml($product->photo)?>"width="50" height="50" />
                </a>
            </p>
        </td>
    </tr>
</table>


<?php
$url = $this->url('product', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>

<form action="<?php echo $url; ?>" method="post">
	<div>
	    <input type="hidden" name="id" value="<?php echo (int) $product->id; ?>" />
	    <input type="submit" name="del" value="Yes" />
	    <input type="submit" name="del" value="No" />
	</div>
</form>