<?php
$title = 'Edit product';
$this->headTitle($title);
?>
 
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'product',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();
?>

<?= $this->form()->openTag($form)?>
<?=$this->formHidden($form->get('id'))?>
<div class="form-group">
	<?=$this->formRow($form->get('name'))?>
</div>

<div class="form-group">
	<?=$this->formRow($form->get('description'))?>
</div>

<div class="form-group">
	<?=$this->formRow($form->get('price'))?>
</div>

<div class="form-group">
	<?=$this->formRow($form->get('photo'))?>
</div>

<div class="form-group">
	<?=$this->formSubmit($form->get('submit'))?>
</div>

<?=$this->form()->closeTag()?>