<?php 
$title = 'My products';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('product', ['action' => 'add']) ?>">Add new product</a>
</p>

<table class="table">
<tr>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
    <th>Photo</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($products as $product) : ?>
    <tr>
        <td><?= $this->escapeHtml($product->name) ?></td>
        <td><?= $this->escapeHtml($product->description) ?></td>
        <td><?= $this->escapeHtml($product->price) ?></td>
        <td><?= $this->escapeHtml($product->photo) ?></td>
        <td>
        	<a href="<?php echo $this->url('product', array('action'=>'edit', 'id' => $product->id));?>">Edit</a>
         	<a href="<?php echo $this->url('product', array('action'=>'delete', 'id' => $product->id));?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>