<?php 
$title = 'My products';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<?php // view helper
     if ($user = $this->identity()) {
         echo 'Logged in as ' . $this->escapeHtml($user->usr_name);
     }
?>  

<a href="<?php echo $this->url('auth/default', array('controller' => 'index', 'action' => 'logout'));?>">
    <?php echo $this->translate('Logout'); ?>
</a> 

<p>
    <a href="<?= $this->url('product', ['action' => 'add']) ?>">Add new product</a>
</p>

<table class="table">
<tr>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
    <th>Photo</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($products as $product) : ?>
    <tr>
        <td><?= $this->escapeHtml($product->name) ?></td>
        <td><?= $this->escapeHtml($product->description) ?></td>
        <td><?= $this->escapeHtml($product->price) ?></td>
        <td>
            <a href="<?= $this->escapeHtml($product->photo) ?>">
                <img src="<?= $this->escapeHtml($product->photo) ?>" width="50" height="50" />
            </a>
        </td>
        <td>
        	<a href="<?php echo $this->url('product', array('action'=>'edit', 'id' => $product->id));?>">Edit</a>
         	<a href="<?php echo $this->url('product', array('action'=>'delete', 'id' => $product->id));?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>