<h1>Login </h1>
<?php echo $this->escapeHtml($this->messages); ?>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('auth/default', array('controller' => 'index', 'action' => 'login')));
$form->prepare();
?>

<?= $this->form()->openTag($form)?>

<div class="form-group">
	<?=$this->formRow($form->get('usr_name'))?>
</div>

<div class="form-group">
	<?=$this->formRow($form->get('usr_password'))?>
</div>

<div class="form-group">
	<?=$this->formRow($form->get('rememberme'))?>
</div>

<div class="form-group">
	<?=$this->formSubmit($form->get('submit'))?>
</div>

<?=$this->form()->closeTag()?>

<?php // view helper
    if ($user = $this->identity()) {
        echo 'Logged in as ' . $this->escapeHtml($user->usr_name);
?>		
 | <a href="<?php echo $this->url('auth/default', array('controller' => 'index', 'action' => 'logout'));?>"><?php echo $this->translate('Logout'); ?></a> 
<?php
    } else {
        echo 'Not logged in';
    }
?>
